/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package velov.vue;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import swing.modele.ModeleTableList;
import velov.modele.ArrondissementVille;
import velov.modele.Station;

/**
 *
 * @author Jean-Mouloud
 */
public class FrameVelov extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    boolean modeEdition;
    ModeleTableList modeleTableList;
    AbstractListModel modeleList;
    public FrameVelov() {
        modeleTableList = new ModeleTableList();
        modeleList = new AbstractListModel() {
            private final List<ArrondissementVille> listeArrondissement;

            {
                this.listeArrondissement = new ArrayList<>();
                this.listeArrondissement.add(new ArrondissementVille(1, "Lyon 1er arrondissement"));
                this.listeArrondissement.add(new ArrondissementVille(2, "Lyon 2eme arrondissement"));
                this.listeArrondissement.add(new ArrondissementVille(3, "Lyon 3eme arrondissement"));
                this.listeArrondissement.add(new ArrondissementVille(4, "Lyon 4eme arrondissement"));
                this.listeArrondissement.add(new ArrondissementVille(5, "Lyon 5eme arrondissement"));
                this.listeArrondissement.add(new ArrondissementVille(6, "Lyon 6eme arrondissement"));
                this.listeArrondissement.add(new ArrondissementVille(7, "Lyon 7eme arrondissement"));
                this.listeArrondissement.add(new ArrondissementVille(8, "Lyon 8eme arrondissement"));
                this.listeArrondissement.add(new ArrondissementVille(9, "Lyon 9eme arrondissement"));
            }

            @Override
            public int getSize() {
                return this.listeArrondissement.size();
            }

            @Override
            public Object getElementAt(int i) {
                return this.listeArrondissement.get(i).getNomArrondissementVille();
            }
        };
        initComponents();
        modeEdition = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boutonCreer = new javax.swing.JButton();
        boutonSupprimer = new javax.swing.JButton();
        numeroStation = new javax.swing.JTextField();
        nomStation = new javax.swing.JTextField();
        localisation = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        menuFichierOuvrir = new javax.swing.JMenuItem();
        menuFichierSauvegarder = new javax.swing.JMenuItem();
        menuFichierQuitter = new javax.swing.JMenuItem();
        menuApropos = new javax.swing.JMenu();
        aPropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(modeleTableList);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Numéro Station :");

        jLabel2.setText("Nom station :");

        jLabel3.setText("Numero Arrondissement :");

        jLabel4.setText("Localisation :");

        boutonCreer.setText("Créer");
        boutonCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCreerActionPerformed(evt);
            }
        });

        boutonSupprimer.setText("Supprimer");
        boutonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSupprimerActionPerformed(evt);
            }
        });

        numeroStation.setEnabled(false);

        nomStation.setEnabled(false);

        localisation.setEnabled(false);

        jList1.setModel(modeleList);
        jList1.setDoubleBuffered(true);
        jList1.setEnabled(false);
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numeroStation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomStation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(localisation))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boutonCreer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(boutonSupprimer)
                        .addGap(175, 175, 175))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(localisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numeroStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(nomStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonCreer)
                    .addComponent(boutonSupprimer))
                .addContainerGap())
        );

        menuFichier.setText("Fichier");

        menuFichierOuvrir.setText("Ouvrir");
        menuFichierOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFichierOuvrirActionPerformed(evt);
            }
        });
        menuFichier.add(menuFichierOuvrir);

        menuFichierSauvegarder.setText("Sauvergarder");
        menuFichier.add(menuFichierSauvegarder);

        menuFichierQuitter.setText("Quitter");
        menuFichierQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFichierQuitterActionPerformed(evt);
            }
        });
        menuFichier.add(menuFichierQuitter);

        jMenuBar1.add(menuFichier);

        menuApropos.setText("?");

        aPropos.setText("A propos");
        menuApropos.add(aPropos);

        jMenuBar1.add(menuApropos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFichierQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFichierQuitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFichierQuitterActionPerformed

    private void boutonCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCreerActionPerformed
        if(!modeEdition){
            boutonCreer.setText("Ok ?");
            nomStation.setEnabled(true);
            numeroStation.setEnabled(true);
            localisation.setEnabled(true);
            jList1.setEnabled(true);
            modeEdition=true;
        }
        else{
            int numArrond = jList1.getSelectedIndex()+1;
            if(numeroStation.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Il faut remplir le numero station", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            else if(nomStation.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Il faut remplir le nom de la station", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            else if(localisation.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Il faut remplir la localisation", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            else if(numArrond==0){
                JOptionPane.showMessageDialog(this, "Il faut selectionner un arrondissement", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
            else{
                modeleTableList.addStation(new Station(numeroStation.getText(),nomStation.getText(),localisation.getText(),numArrond));
                boutonCreer.setText("Créer");
                nomStation.setEnabled(false);
                numeroStation.setEnabled(false);
                localisation.setEnabled(false);
                jList1.setEnabled(false);
                modeEdition=false;
            }
        }
    }//GEN-LAST:event_boutonCreerActionPerformed

    private void boutonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSupprimerActionPerformed
        
    }//GEN-LAST:event_boutonSupprimerActionPerformed

    private void menuFichierOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFichierOuvrirActionPerformed
        JFileChooser ouvrirFichier = new JFileChooser();
        ouvrirFichier.showDialog(this, "Ouvrir");
        if(ouvrirFichier.getSelectedFile() != null){
            File fichier = ouvrirFichier.getSelectedFile();
            
        }
    }//GEN-LAST:event_menuFichierOuvrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVelov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVelov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVelov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVelov.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVelov().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aPropos;
    private javax.swing.JButton boutonCreer;
    private javax.swing.JButton boutonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField localisation;
    private javax.swing.JMenu menuApropos;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JMenuItem menuFichierOuvrir;
    private javax.swing.JMenuItem menuFichierQuitter;
    private javax.swing.JMenuItem menuFichierSauvegarder;
    private javax.swing.JTextField nomStation;
    private javax.swing.JTextField numeroStation;
    // End of variables declaration//GEN-END:variables
}
